### ISSUE TITLE
compilation issue - strlen not defined

### ISSUE THREAD

**Issue by mmllee** [welinder/cubam#1]
in my setup (linux debian squeeze 64bit ) the installation process fails on:
...
src/BinaryModel.cpp: In member function ‘virtual void BinaryModel::load_data(const char*)’:
src/BinaryModel.cpp:53: error: ‘strlen’ was not declared in this scope
error: command 'gcc' failed with exit status 1

adding 
# include <cstring>

into BinaryModel.cpp fixes the problem

Regards
lemm

**Comment by beijbom** [comment]
Had the same problem on my Ubuntu machine. Was an easy fix though, I just added #import <cstring> to the beginning of BinaryModel.cpp.

**Comment by welinder** [comment]
I've pushed a fix to the issue. Let me know if it remains.
